### PR TITLE
Ob/issue 9 setup zoom controls 

### PR DESCRIPTION
**Pull request by Netdreion**
thank you for taking the time to review my changes. In this pull request, I have added the zoom controls to the Map component using Hero Icons. I have also used the ZoomControl component provided by react-leaflet to render the zoom controls.

I made these changes in response to the requirements outlined in the Figma file and the instructions provided. I believe that the new zoom controls will improve the user experience of the Map component.

### CODE REVIEW

**Comment by toreylittlefield** [comment]
@Netdreion lol did you use chaptgpt to write the description?

**Comment by Netdreion** [comment]
for sure lol

**Comment by toreylittlefield** [comment]
@Netdreion you have to create a new branch  you're on the old tailwind setup branch

**Comment by Netdreion** [comment]
> @Netdreion you have to create a new branch you're on the old tailwind setup branch
 
yes , realized that.

**Comment by Netdreion** [comment]
> for sure lol

ok , i will

**Comment by toreylittlefield** [comment]
@Netdreion thanks. It looks good I can see the changes. Just you gotta create a new branch from `main` branch and put your changes there.

If you need help let me know bro and nice work!!

**Comment by toreylittlefield** [comment]
@Netdreion I'll close this pull request so you can make a new one with the new correct branch 🙇‍♂️

**Pull request closed without merging**
