### PR TITLE
added search bar component in report form

### PR DESCRIPTION
**Pull request by HarshMakadiya**
I have added a search bar component in the report form area and I think UpdateView is necessary because it renders in the ReportForm component so I think its feasible to keep it there might be of some use in future!

### CODE REVIEW

**Review by toreylittlefield — CHANGES_REQUESTED** [review]
@HarshMakadiya thanks. That works 😀

But can you please remove the commented out code.

In addition, there is one other change that needs to be implemented. I should have been more specific in the issue.

When the user searches a new location and selects one in the drop-down and confirms the updated location, the lat and lng in the location view should reflect the changes. That way the new selected location is updated in the store.

 The marker created when the form is submitted should reflect this new location correctly.

**Comment by HarshMakadiya** [comment]
@toreylittlefield Sure, I will complete the required changes and update you regarding the same.

**Comment by HarshMakadiya** [comment]
Hey @toreylittlefield, I have just updated the code. Please look into it.

**Review by HarshMakadiya — COMMENTED** [review]
Hey @toreylittlefield, I have just updated the code. Please look into it and tell me if any updates are required.

**Comment by toreylittlefield** [comment]
@HarshMakadiya one other thing that should also be updated is when the location is selected from search it should update the view in the map and center the marker on that lat and lng.

If that's not possible no problem and we can punt that issue.


Example: searched and selected "new York city" but map did not update the location or the marker

**Comment by HarshMakadiya** [comment]
@toreylittlefield can you please check the updated PR and review it? I have updated the map as per the search.

**Comment by toreylittlefield** [comment]
> Hey @toreylittlefield can you please check the updated PR and review it? I have updated the map as per the search.

Thanks looking good! Just a few NIT picks 👍

**Comment by HarshMakadiya** [comment]
@toreylittlefield sure! let me update that real quick.

**Review by MacAndersonUche — CHANGES_REQUESTED** [review]

**Comment by toreylittlefield** [comment]
@HarshMakadiya thanks for the work on this. I'll go ahead and make those few minor changes and get this merged in.

Much appreciated 👍

**Comment by toreylittlefield** [comment]
@HarshMakadiya thanks for your contribution! 🥇

**Pull request merged**
